server:
    port: 8080

#spring
spring:
  mail:
    host: smtp.exmail.qq.com
    username: jeeopen@jeeopen.com
    password: 您的密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true